gateway fix
MyRobotLab/myrobotlab pull request #1320
Opened 2023-07-25 14:01 UTC by supertick

![image](https://github.com/MyRobotLab/myrobotlab/assets/1266144/4ba04440-ef66-460a-a606-5863860bb17d)

2023-07-25 15:12 UTC, AutonomicPerfectionist requested changes

2023-07-25 15:12 UTC, AutonomicPerfectionist commented on src/main/java/org/myrobotlab/net/WsClient.java
> +        // ignore Atmosphere does a weird sending of X characters I assume
It's actually MRL doing that, there's a heartbeat timer somewhere in the WebGui service from what I remember

2023-07-25 15:12 UTC, AutonomicPerfectionist commented on src/main/java/org/myrobotlab/service/interfaces/Gateway.java
> +                    CodecUtils.toJson(new DescribeQuery(Platform.getLocalInstance().getId(), connId))
This is going to result in triple encoding of the message again, we removed that because it caused some bug awhile ago

2023-07-25 15:12 UTC, AutonomicPerfectionist commented on src/main/resources/resource/WebGui/app/mrl.js
> +        hello = JSON.parse(request.data[1])
What's this for? The triple encoding?

2023-07-25 15:19 UTC, supertick commented on src/main/java/org/myrobotlab/net/WsClient.java
> +        // ignore Atmosphere does a weird sending of X characters I assume
Its not MRL its nettosphere/atmosphere

2023-07-25 15:20 UTC, supertick commented on src/main/java/org/myrobotlab/service/interfaces/Gateway.java
> +                    CodecUtils.toJson(new DescribeQuery(Platform.getLocalInstance().getId(), connId))
I guess the flow needs to be followed, but the current error is easy to reproduce
Connect a runtime with another runtime + webgui

2023-07-26 01:06 UTC, supertick commented on src/main/resources/resource/WebGui/app/mrl.js
> +        hello = JSON.parse(request.data[1])
parse decodes

2023-07-26 13:41 UTC, supertick commented on src/main/java/org/myrobotlab/service/interfaces/Gateway.java
> +                    CodecUtils.toJson(new DescribeQuery(Platform.getLocalInstance().getId(), connId))
fixed correctly, thanks !

2023-07-26 13:41 UTC, supertick commented on src/main/resources/resource/WebGui/app/mrl.js
> +        hello = JSON.parse(request.data[1])
removed .. thanks !

2023-07-26 13:41 UTC, merged