Discordbot
MyRobotLab/myrobotlab pull request #953
Opened 2021-10-13 18:18 UTC by kwatters

initial impl for the diffbot service.

2021-10-14 16:16 UTC, supertick requested changes

2021-10-14 16:16 UTC, supertick commented on src/main/java/org/myrobotlab/service/DiscordBot.java
> +
This should follow the attach pattern
ProgramAB has an example ...
As you said - there currently isn't an interface for a brain - but attach can use the actual class until we get there ..

2021-10-14 16:16 UTC, supertick commented on src/main/java/org/myrobotlab/service/DiscordBot.java
> +    DiscordBotConfig config = (DiscordBotConfig)c;
cool config with token ... :thinking:  config should be enhanced to understand sensitive data - then mebbe the security service can go away, at least its in the user directory and not likely to get pushed to github

2021-10-14 16:16 UTC, supertick commented on src/main/java/org/myrobotlab/service/DiscordBot.java
> +    /// TODO: this isn't good OO programming to have to do it this way.
// Noted ... future prs

2021-10-14 16:16 UTC, supertick commented on src/main/java/org/myrobotlab/service/DiscordBot.java
> +    bot = jda.build();
bot is not used

2021-10-14 16:16 UTC, supertick commented on src/main/java/org/myrobotlab/service/DiscordBot.java
> + */
Shouldn't this be a TextListener and TextPublisher ?  or we need new interfaces ?

2021-10-14 16:16 UTC, supertick commented on src/main/java/org/myrobotlab/discord/MrlDiscordBotListener.java
> + */
It looks like ListenerAdapter implements the EventListener interface 
If given a choice Discordbot should use the interface instead of creating a separate class - but considering the number of methods (a friggin boatload of callbacks) I can understand the desire to extend from the abstract ListenerAdapter..
But, It looks like **all** are just empty implementations except for one or two...

2021-10-14 16:16 UTC, supertick commented on src/main/java/org/myrobotlab/discord/MrlDiscordBotListener.java
> +
This should publish text right ?

2021-10-14 16:16 UTC, supertick commented on src/main/java/org/myrobotlab/discord/MrlDiscordBotListener.java
> +    if (shouldIRespond) {
use config

2021-10-14 16:16 UTC, supertick commented on src/main/java/org/myrobotlab/discord/MrlDiscordBotListener.java
> +
Shouldn't this be configured and behave more or less like the HtmlFilter ?
ie. be a TextPublisher and a TextListener and just be attached so its wired as desired ?

2021-10-14 16:16 UTC, supertick commented on src/main/java/org/myrobotlab/framework/repo/Repo.java
> +
bummer

2021-10-14 16:44 UTC, kwatters commented on src/main/java/org/myrobotlab/discord/MrlDiscordBotListener.java
> +    if (shouldIRespond) {
this is controlling what messages should be responded to... for direct communications, the bot will always respond ...  for a message received in the discord channel, it only responds if the bot is mentioned.... and then again only responds if the message did not come from another bot ...  we could probably externalize a little of that behavior to config

2021-10-18 15:08 UTC, supertick approved these changes

2021-10-18 19:18 UTC, kwatters commented on src/main/java/org/myrobotlab/discord/MrlDiscordBotListener.java
> + */
no easy way to wire it in otherwise.

2021-10-18 19:19 UTC, kwatters commented on src/main/java/org/myrobotlab/discord/MrlDiscordBotListener.java
> +
it does now :)

2021-10-18 19:19 UTC, kwatters commented on src/main/java/org/myrobotlab/discord/MrlDiscordBotListener.java
> +
UtterancePublisher and UtteranceListener are born.

2021-10-18 19:19 UTC, kwatters commented on src/main/java/org/myrobotlab/service/DiscordBot.java
> + */
new interfaces!

2021-10-18 19:20 UTC, kwatters commented on src/main/java/org/myrobotlab/service/DiscordBot.java
> +    DiscordBotConfig config = (DiscordBotConfig)c;
agreed.. "secret store" or other integration is a nice to have..

2021-10-18 19:20 UTC, kwatters commented on src/main/java/org/myrobotlab/service/DiscordBot.java
> +    bot = jda.build();
i've added a shutdown hook.

2021-10-18 19:21 UTC, kwatters commented on src/main/java/org/myrobotlab/service/DiscordBot.java
> +
hopefully the utterance interfaces will suffice for now.

2021-10-19 05:51 UTC, merged